# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jokes-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca262c34d1ec42b99da296999b543c4f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5bf69965fdd0439ea5d945a9a9a2a867 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca262c34d1ec42b99da296999b543c4f }}/joke-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jokes-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e937bdbb51c94e0cad6663e58fe10266 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca262c34d1ec42b99da296999b543c4f }}/joke-service:${{ github.sha }}'